### ISSUE TITLE
EncryptUtil

### ISSUE THREAD

**Issue by hiei17** [michaelliao/cryptocurrency#3]
java.security.InvalidKeyException: Illegal key size

	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.itranswarp.bitcoin.wallet.util.EncryptUtil.encrypt(EncryptUtil.java:34)
	at com.itranswarp.bitcoin.wallet.util.EncryptUtilTest.testEncryptAndDecrypt(EncryptUtilTest.java:17)

**Comment by michaelliao** [comment]
patch your jdk with jce unlimited policy
